// <auto-generated />
using System;
using Elumatec.Tijdregistratie.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elumatec.Tijdregistratie.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260203134006_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("Elumatec.Tijdregistratie.Models.Contactpersoon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefoonNummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("contactpersonen", (string)null);
                });

            modelBuilder.Entity("Elumatec.Tijdregistratie.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Content")
                        .HasColumnType("BLOB");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("InterventieId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InterventieId");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("Elumatec.Tijdregistratie.Models.Interventie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AantalCalls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bedrijfsnaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContactpersoonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DatumRecentsteCall")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExterneNotities")
                        .HasColumnType("TEXT");

                    b.Property<int>("InterneMedewerkerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InterneNotities")
                        .HasColumnType("TEXT");

                    b.Property<string>("Machine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotaleLooptijd")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContactpersoonId");

                    b.HasIndex("InterneMedewerkerId");

                    b.ToTable("interventies", (string)null);
                });

            modelBuilder.Entity("Elumatec.Tijdregistratie.Models.Medewerker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("medewerkers", (string)null);
                });

            modelBuilder.Entity("Elumatec.Tijdregistratie.Models.Document", b =>
                {
                    b.HasOne("Elumatec.Tijdregistratie.Models.Interventie", "Interventie")
                        .WithMany("Documents")
                        .HasForeignKey("InterventieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interventie");
                });

            modelBuilder.Entity("Elumatec.Tijdregistratie.Models.Interventie", b =>
                {
                    b.HasOne("Elumatec.Tijdregistratie.Models.Contactpersoon", "Contactpersoon")
                        .WithMany("Interventies")
                        .HasForeignKey("ContactpersoonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Elumatec.Tijdregistratie.Models.Medewerker", "InterneMedewerker")
                        .WithMany()
                        .HasForeignKey("InterneMedewerkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contactpersoon");

                    b.Navigation("InterneMedewerker");
                });

            modelBuilder.Entity("Elumatec.Tijdregistratie.Models.Contactpersoon", b =>
                {
                    b.Navigation("Interventies");
                });

            modelBuilder.Entity("Elumatec.Tijdregistratie.Models.Interventie", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
